language: perl
matrix:
  include:
    - perl: "5.30"
      dist: xenial
    - perl: "5.26"
      dist: xenial
    - perl: "5.22"
      dist: trusty
    - perl: "5.20"
      dist: trusty
    - perl: "5.18"
      dist: trusty
    - perl: "5.16"
      dist: precise
    - perl: "5.14"
      dist: precise
    - perl: "5.12"
      dist: precise
    - perl: "5.10"
      dist: precise
    - perl: "5.8"
      dist: precise

before_install:
  - cpanm --quiet --notest MIME::Parser MIME::Lite
before_script:
  - (cd t && ln -s ../xt/travis-ci.t travis-ci.t)

branches:
 except:
  - /appveyor/
